plugins {
    id 'nva.java-conventions'
}

nva {
    errorprone {
        allErrorsAsWarnings = false
    }
    pmd {
        rulesetFile = rootProject.file('config/pmd/ruleset.xml')
    }
    spotless {
        enabled = true
    }
}

test {
    environment("ALLOWED_ORIGIN", "*")
    environment("API_HOST", "api.fake.nva.aws.unit.no")
    environment("COGNITO_AUTHORIZER_URLS", "http://localhost:3000")
    environment("LOG4J_CONFIGURATION_FILE", "classpath:nva-log4j2.xml")
    environment("LOG_LEVEL", "info")
    environment("TABLE_NAME", "nonExistentTable")
}
