extends:
  - spectral:oas

rules:
  # Disabled because we use non-standard AWS extensions
  oas3-operation-security-defined: off

overrides:
  - files:
      - "docs/openapi.yaml#/paths/~1%7BcristinId%2B%7D"
    rules:
      # AWS API Gateway extension uses greedy path parameters like {cristinId+} which isn't standard OpenAPI
      path-params: off
