version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - pip install wheel # Temp workaround: https://github.com/aws/aws-cli/issues/8036
      - pip install "Cython<3.0" "pyyaml<6" --no-build-isolation  # Temp workaround: https://github.com/aws/aws-cli/issues/8036
      - pip3 install aws-sam-cli
  build:
    commands:
      - sam build
      - sam package --s3-bucket $S3_BUCKET --output-template-file packaged.yaml
artifacts:
  files:
    - packaged.yaml