plugins {
    id 'nva.person.preferences.java-conventions'
    id 'java-test-fixtures'
}

dependencies {
    api(nvaCatalog.aws.sdk2.dynamo)
    api(nvaCatalog.jackson.annotations)
    api(nvaCatalog.jackson.databind)
    api(nvaLibs.apigateway)
    implementation(nvaCatalog.aws.sdk2.dynamodbenhanced)
    implementation(nvaLibs.core)
    implementation(nvaLibs.json)
    testFixturesApi(nvaCatalog.aws.sdk2.dynamo)
    testFixturesApi(nvaCatalog.junit.jupiter.api)
    testFixturesImplementation(nvaCatalog.aws.sdk2.dynamodblocal)
    testImplementation(nvaCatalog.hamcrest)
    testImplementation(nvaCatalog.jackson.core)
    testImplementation(nvaCatalog.junit.jupiter.api)
    testImplementation(nvaLibs.testutils)
}
