plugins {
    id 'nva.person.preferences.java-conventions'
}

dependencies {
    api(nvaCatalog.aws.lambda.core)
    api(nvaCatalog.jackson.annotations)
    api(nvaCatalog.jackson.databind)
    api(nvaLibs.apigateway)
    api(nvaLibs.core)
    api(project(":preferences-commons"))
    implementation(nvaCatalog.aws.sdk2.dynamo)
    testImplementation(nvaCatalog.hamcrest)
    testImplementation(nvaCatalog.httpcore4)
    testImplementation(nvaCatalog.jackson.core)
    testImplementation(nvaCatalog.junit.jupiter.api)
    testImplementation(nvaCatalog.mockito.core)
    testImplementation(nvaCatalog.zalando)
    testImplementation(nvaLibs.json)
    testImplementation(nvaLibs.testutils)
    testImplementation(testFixtures(project(":preferences-commons")))
}
